### ISSUE TITLE
Use rawgithub.com instead of raw.github.com in site_base.html

### ISSUE THREAD

**Issue by AfzalivE** [eldarion/eldarion-ajax-demo#3]
Latest Chrome dev says:

Refused to execute script from 'https://raw.github.com/eldarion/bootstrap-ajax/master/js/bootstrap-ajax.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

I believe that is because most things served from raw.github.com have a text/plain content type, which means HTML won't render, and some browsers won't execute JavaScript or apply CSS.

**Comment by paltman** [comment]
@AfzalivE can you send me a PR?

**Comment by AfzalivE** [comment]
I don't think this is relevant anymore.
