### ISSUE TITLE
Why not just use request.session?

### ISSUE THREAD

**Issue by jessep** [eldarion/eldarion-ajax-demo#4]
On line [107 of views.py](https://github.com/eldarion/eldarion-ajax-demo/blob/master/demo/views.py#L107) There's this:

`session = Session.objects.get(session_key=request.session.session_key)`

I assume there's a good reason for this, rather than doing:

`session = request.session`

Just wanted to be enlightened about what that was. Thanks!

**Comment by paltman** [comment]
@jessep no reason
